name: Build & Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - run: npm ci
    - run: npm run build -- --production
    - run: npm run build-service -- --env production
    - run: npm run package
    - run: npm run manifest

    - name: Upload Release assets
      id: upload-release-assets
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ steps.tagName.outputs.tag }}
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        artifacts: *.ipk,org.webosbrew.hbchannel.manifest.json
